version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '4200:4200'
    environment:
      DATABASE_URL: 'postgresql://postgres:password@db:5432/mydatabase'
      JWT_SECRET: 'your_jwt_secret'
    depends_on:
      - db
    command: >
      sh -c "
      npx prisma generate &&
      npx prisma db push &&
      npx prisma db pull &&
      npm run start:prod
      "

  db:
    image: postgres:15-alpine
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mydatabase
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
